version: '3.8'

services:
  alwurts-cms:
    container_name: alwurts-cms
    build:
      context: ./alwurts-cms
      dockerfile: prod.Dockerfile
      args:
        NODE_ENV: production
        POSTGRES_HOST: alwurts-cms-db
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        AUTH_URL: ${AUTH_URL}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
        AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
        AUTH_DRIZZLE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@alwurts-cms-db:5432/${POSTGRES_DB}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_REGION: ${S3_REGION}
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - alwurts-cms-db

  alwurts-cms-db:
    container_name: alwurts-cms-db
    image: postgres:13
    volumes:
      - alwurts_cms_postgres_data:/data/postgres
    ports:
      - 3254:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres

volumes:
  alwurts_cms_postgres_data: