version: '3.8'

services:
  studio:
    container_name: alwurts-cms-drizzle_studio
    restart: always
    build:
      context: ./alwurts-cms
      dockerfile: studio.Dockerfile
    ports:
      - "4983:4983"
    depends_on:
      - alwurts-cms-db
    environment:
      - POSTGRES_HOST=alwurts-cms-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: drizzle-kit studio --host=0.0.0.0
    volumes:
      - studio_node_modules:/app/node_modules

  alwurts-cms:
    container_name: alwurts-cms
    build:
      context: ./alwurts-cms
      dockerfile: dev.Dockerfile
    ports:
      - "2267:2267"
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - POSTGRES_HOST=alwurts-cms-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - AUTH_DRIZZLE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@alwurts-cms-db:5432/${POSTGRES_DB}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
    volumes:
      - ./alwurts-cms/src:/app/src
      - ./alwurts-cms/public:/app/public
    depends_on:
      - alwurts-cms-db

  alwurts-cms-db:
    container_name: alwurts-cms-db
    image: postgres:13
    volumes:
      - alwurts_cms_postgres_data:/data/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres

volumes:
  alwurts_cms_postgres_data:
  studio_node_modules: